server:
  port: 8080


spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 添加数据库密码
    url: jdbc:mysql://localhost:3306/uoice?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  #    password:

  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.uoice.music.bean
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true



